#!/usr/bin/env fish

echo "=== Excalibur (exh) 安装完成 ==="
echo ""
echo "✓ 已安装函数: exh (Excalibur History)"
echo "✓ Ctrl+R 已自动绑定"
echo ""
echo "使用方法："
echo ""
echo "  1. 命令方式:"
echo "     exh"
echo ""
echo "  2. 快捷键:"
echo "     按 Ctrl+R"
echo ""
echo "  3. 独立运行:"
echo "     excalibur"
echo ""
echo "在 TUI 中："
echo "  Enter   - 选中命令（插入到命令行，可编辑）"
echo "  Ctrl+O  - 直接执行命令（无需确认）"
echo "  /       - 搜索"
echo "  s       - 切换排序"
echo "  Esc/q   - 退出"
echo ""
echo "现在运行以下命令测试："
echo "  source ~/.config/fish/config.fish"
echo "  exh"
echo ""
